### ISSUE TITLE
RSAESCryptor SecTrustCreateWithCertificates certificateRef

### ISSUE THREAD

**Issue by farodig** [bigsan/RSAESCryptor#2]
//RSAESCryptor line 100:
OSStatus status = SecTrustCreateWithCertificates(certificateRef, policyRef, &trustRef);
//error:
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
certificateRef = 0x0
//my code in swift:
var filePath = NSBundle.mainBundle().pathForResource("myfile", ofType: "pem")
//file read correct
var cryptor = RSAESCryptor.sharedCryptor()
cryptor.loadPublicKey(filePath!) // error

**Comment by bigsan** [comment]
It looks like the certificate file is in PEM format, which is not supported by `SecCertificateCreateWithData()`. It supports DER format only.

Have a look at https://www.sslshopper.com/ssl-converter.html for how to do the conversion.
